### ISSUE TITLE
缺少dyld_shared_cache_xxxx

### ISSUE THREAD

**Issue by renguochao** [Zuikyo/iOS-System-Symbols#1]
缺少dyld_shared_cache_xxxx，导致libdispatch.dylib、libsystem_kernel.dylib和libsystem_pthread.dylib 解不出来

**Comment by Zuikyo** [comment]
文档里有说明，`xxx-Caches`后缀的压缩包就是`dyld_shared_cache_xxxx`文件。
把你的crash report发上来我试试。我没遇到过解析不出来的情况。
`dyld_shared_cache_xxxx`只是苹果把对应CPU版本的系统库弄成了一个大文件，加快执行速度，里面的内容提取出来以后是和符号文件一样的。

**Comment by Zuikyo** [comment]
最近发现原来是8.1 (12B411) 和 8.0 (12A365)的符号文件无效，导致符号化失败了。这两个是从Xcode 6 的SDK里取出来的，文件大小不对。看来从Xcode 6开始已经没有真机的SDK了。我从固件中提取了armv7s和armv7的符号，arm64的就只能从真机上获取了，现在缺失中。
