### ISSUE TITLE
tvOS system symbol

### ISSUE THREAD

**Issue by feelform** [Zuikyo/iOS-System-Symbols#10]
I want to symbolize crash report of tvOS app. Can I use the crash report of the tvOS app with  iOS system symbols?

Or should I extract the tvOS system symbol?

I want to hear your opinion.

**Comment by Zuikyo** [comment]
I think you need to extract the tvOS symbol. 
Most tvOS firmwares have different build versions. You need symbol file with the same build version of the crash report, like `14C82 ` in `10.2 (14C82)`.
