### ISSUE TITLE
Error: dyld shared cache code signature directory num slots is incorrect.

### ISSUE THREAD

**Issue by li8911255** [Zuikyo/iOS-System-Symbols#12]
今天提取13.2 Beta 的arm64e符号文件时报这个错误，dsc_extractor.cpp里也没搜到这个错误，不知道各位大牛有没有遇到？

**Comment by luckyCity** [comment]
mee to

**Comment by jwssdwed** [comment]
The reason is because of old Xcode version. For 12.3.2 (2019/10/25), old Xcode version cannot extract new symbols.

**Comment by Zuikyo** [comment]
[dsc_extractor](https://opensource.apple.com/source/dyld/dyld-655.1.1/launch-cache/dsc_extractor.cpp.auto.html) uses `dsc_extractor.bundle` in Xcode.app.
This error is from `dsc_extractor.bundle` (`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/dsc_extractor.bundle`).
You need to update to Xcode 11.

**Comment by luckyCity** [comment]
> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/



> [dsc_extractor](https://opensource.apple.com/source/dyld/dyld-655.1.1/launch-cache/dsc_extractor.cpp.auto.html) uses `dsc_extractor.bundle` in Xcode.app.
> This error is from `dsc_extractor.bundle` (`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/dsc_extractor.bundle`).
> You need to update to Xcode 11.

I'm using Version 11.2 beta (11B41), but it doesn't work

**Comment by Zuikyo** [comment]
> > /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/
> 
> > [dsc_extractor](https://opensource.apple.com/source/dyld/dyld-655.1.1/launch-cache/dsc_extractor.cpp.auto.html) uses `dsc_extractor.bundle` in Xcode.app.
> > This error is from `dsc_extractor.bundle` (`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/dsc_extractor.bundle`).
> > You need to update to Xcode 11.
> 
> I'm using Version 11.2 beta (11B41), but it doesn't work

Your beta Xcode path may be `/Applications/Xcode beta.app/`, but `dsc_extractor` always uses `/Applications/Xcode.app/`.
Try to rename your `Xcode beta.app` to `Xcode.app`.

**Comment by luckyCity** [comment]
> > > /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/
> > 
> > 
> > > [dsc_extractor](https://opensource.apple.com/source/dyld/dyld-655.1.1/launch-cache/dsc_extractor.cpp.auto.html) uses `dsc_extractor.bundle` in Xcode.app.
> > > This error is from `dsc_extractor.bundle` (`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/dsc_extractor.bundle`).
> > > You need to update to Xcode 11.
> > 
> > 
> > I'm using Version 11.2 beta (11B41), but it doesn't work
> 
> Your beta Xcode path may be `/Applications/Xcode beta.app/`, but `dsc_extractor` always uses `/Applications/Xcode.app/`.
> Try to rename your `Xcode beta.app` to `Xcode.app`.

Maybe for some other reason, I have changed Xcode bet.app to xcode. app, but it still doesn't work.

**Comment by luckyCity** [comment]
> > > /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/
> > 
> > 
> > > [dsc_extractor](https://opensource.apple.com/source/dyld/dyld-655.1.1/launch-cache/dsc_extractor.cpp.auto.html) uses `dsc_extractor.bundle` in Xcode.app.
> > > This error is from `dsc_extractor.bundle` (`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/dsc_extractor.bundle`).
> > > You need to update to Xcode 11.
> > 
> > 
> > I'm using Version 11.2 beta (11B41), but it doesn't work
> 
> Your beta Xcode path may be `/Applications/Xcode beta.app/`, but `dsc_extractor` always uses `/Applications/Xcode.app/`.
> Try to rename your `Xcode beta.app` to `Xcode.app`.

Maybe for some other reason, I have changed Xcode beta.app to Xcode. app, but it still doesn't work.

**Comment by Zuikyo** [comment]
> > > > /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/
> > > 
> > > 
> > > > [dsc_extractor](https://opensource.apple.com/source/dyld/dyld-655.1.1/launch-cache/dsc_extractor.cpp.auto.html) uses `dsc_extractor.bundle` in Xcode.app.
> > > > This error is from `dsc_extractor.bundle` (`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/dsc_extractor.bundle`).
> > > > You need to update to Xcode 11.
> > > 
> > > 
> > > I'm using Version 11.2 beta (11B41), but it doesn't work
> > 
> > 
> > Your beta Xcode path may be `/Applications/Xcode beta.app/`, but `dsc_extractor` always uses `/Applications/Xcode.app/`.
> > Try to rename your `Xcode beta.app` to `Xcode.app`.
> 
> Maybe for some other reason, I have changed Xcode bet.app to xcode. app, but it still doesn't work.

What's the error message? I'm using the Xcode 11.2.1 GM, and already got iOS 13.2 (17B84). But I haven't try to get iOS beta system.

**Comment by luckyCity** [comment]
> > > > > /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/
> > > > 
> > > > 
> > > > > [dsc_extractor](https://opensource.apple.com/source/dyld/dyld-655.1.1/launch-cache/dsc_extractor.cpp.auto.html) uses `dsc_extractor.bundle` in Xcode.app.
> > > > > This error is from `dsc_extractor.bundle` (`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/dsc_extractor.bundle`).
> > > > > You need to update to Xcode 11.
> > > > 
> > > > 
> > > > I'm using Version 11.2 beta (11B41), but it doesn't work
> > > 
> > > 
> > > Your beta Xcode path may be `/Applications/Xcode beta.app/`, but `dsc_extractor` always uses `/Applications/Xcode.app/`.
> > > Try to rename your `Xcode beta.app` to `Xcode.app`.
> > 
> > 
> > Maybe for some other reason, I have changed Xcode bet.app to xcode. app, but it still doesn't work.
> 
> What's the error message? I'm using the Xcode 11.2.1 GM, and already got iOS 13.2 (17B84). But I haven't try to get iOS beta system.

#13  this is the error i had met , I will use the same environment as yours to test, and if it works I will synchronize here

**Comment by luckyCity** [comment]
> > > > > > /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/
> > > > > 
> > > > > 
> > > > > > [dsc_extractor](https://opensource.apple.com/source/dyld/dyld-655.1.1/launch-cache/dsc_extractor.cpp.auto.html) uses `dsc_extractor.bundle` in Xcode.app.
> > > > > > This error is from `dsc_extractor.bundle` (`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/lib/dsc_extractor.bundle`).
> > > > > > You need to update to Xcode 11.
> > > > > 
> > > > > 
> > > > > I'm using Version 11.2 beta (11B41), but it doesn't work
> > > > 
> > > > 
> > > > Your beta Xcode path may be `/Applications/Xcode beta.app/`, but `dsc_extractor` always uses `/Applications/Xcode.app/`.
> > > > Try to rename your `Xcode beta.app` to `Xcode.app`.
> > > 
> > > 
> > > Maybe for some other reason, I have changed Xcode bet.app to xcode. app, but it still doesn't work.
> > 
> > 
> > What's the error message? I'm using the Xcode 11.2.1 GM, and already got iOS 13.2 (17B84). But I haven't try to get iOS beta system.
> 
> #13 this is the error i had met , I will use the same environment as yours to test, and if it works I will synchronize here

You are right. This issue is related to the xcode version. I can parse iOS13.2 iOS13.3 beta1 with xcode11.2.1
