### ISSUE TITLE
dsc_extractor 无法提取 iOS 13.2 的 dyld_shared_cache_arm64e

### ISSUE THREAD

**Issue by luckyCity** [Zuikyo/iOS-System-Symbols#13]
./dsc_extractor dyld_shared_cache_arm64e ./output

>  Error: dyld shared cache code signature directory num slots is incorrect.
>  dyld_shared_cache_extract_dylibs_progress() => -1

请问您遇到类似问题了吗。 还是我没有升级最新的MACOS 系统有关

**Comment by Zuikyo** [comment]
duplicated with [Error: dyld shared cache code signature directory num slots is incorrect.](https://github.com/Zuikyo/iOS-System-Symbols/issues/12)
