### ISSUE TITLE
ios 13.2.2、ios 13.2.3系统符号表缺失

### ISSUE THREAD

**Issue by huakucha** [Zuikyo/iOS-System-Symbols#14]
ios 13.2.2、ios 13.2.3系统符号表缺失

**Comment by guzuqing** [comment]
Error: dyld shared cache code signature directory num slots is incorrect
dyld_shared_cache_extract_dylibs_progress() => -1
提取13.3arm64e报错，有人遇到过吗？怎么解决

**Comment by Zuikyo** [comment]
Uploaded.
