### ISSUE TITLE
iOS 13.3 (17C54) please!

### ISSUE THREAD

**Issue by hungntv** [Zuikyo/iOS-System-Symbols#15]
Hi,

I followed your steps here: [#extract-symbols-from-firmware](https://github.com/Zuikyo/iOS-System-Symbols#extract-symbols-from-firmware)

The firmware was downloaded here (I did double-check its md5sum after downloading):[https://ipsw.me/download/iPad11,3/17C54](https://ipsw.me/download/iPad11,3/17C54)

But I always get this error while trying to uncompress the firmware file (I used winzip app on mac os 10.14.3):
`Error: unable to write to "/Users/***/Downloads/untitled folder 17/038-03204-069.dmg".`

I tried many of other app to uncompress but the same error

Please help me to uncompress the firmware file or you can upload new symbol for iOS 13.3!

Thank you!

**Comment by Zuikyo** [comment]
Just rename the file `xxx.ipsw` to `xxx.zip`, and uncompress it with the default `Archive Utility` app.

**Comment by Zuikyo** [comment]
I also failed to uncompress this file.

**Comment by Zuikyo** [comment]
13.3 (17C54) is uploaded.
