### ISSUE TITLE
13.1.1 (17A854) Symbol files please

### ISSUE THREAD

**Issue by ArunaYarra** [Zuikyo/iOS-System-Symbols#16]
Hi,

Could you please add 13.1.1 (17A854) and 13.2.1 (17B90) in your google drive?
Because we were unable to download the 13.1.1 and 13.2.1 firmware files to downgrade/upgrade the devices to get these version symbol files.

Thanks,
Aruna

**Comment by Zuikyo** [comment]
My PC is not near by now. You can get symbol files from firmware file directly. A device is not needed.
See [Extract Symbols from Firmware](https://github.com/Zuikyo/iOS-System-Symbols#extract-symbols-from-firmware).

**Comment by izmal** [comment]
13.1.1 (17A854) here https://yadi.sk/d/EItpH_24_gbgCA
I don't have 13.2.1 (17B90) because this version was just for iPad.

**Comment by Aruna-Sree** [comment]
> 13.1.1 (17A854) here https://yadi.sk/d/EItpH_24_gbgCA
> I don't have 13.2.1 (17B90) because this version was just for iPad.

Thank you so much.

**Comment by Aruna-Sree** [comment]
> My PC is not nearby now. You can get symbol files from the firmware file directly. A device is not needed.
> See [Extract Symbols from Firmware](https://github.com/Zuikyo/iOS-System-Symbols#extract-symbols-from-firmware).

Thanks for the update. But we were unable to download the firmware files from any blog as we are getting "Access Denied" error.

**Comment by izmal** [comment]
I tried to download firmware and alright.
I used https://ipsw.me/

**Comment by Aruna-Sree** [comment]
> I tried to download firmware and alright.
> I used https://ipsw.me/

Yea we are also using same blog to download. Anyhow thanks for sharing 13.1.1 symbol files.. 13.2.1 is for Homepod only right so we are ignoring it currently.

**Comment by Zuikyo** [comment]
13.1.1 (17A854) is uploaded.
