### ISSUE TITLE
iOS 13.4 iOS System symbol files

### ISSUE THREAD

**Issue by ArunaYarra** [Zuikyo/iOS-System-Symbols#18]
Hi,

Please upload iOS 13.4 system symbol files.

Thanks,
Aruna

**Comment by ArunaYarra** [comment]
Hey,

I'm getting arm64e only for iOS 13.4 from the IPSW file.
could you please help me from where we can get remaining arches IPSW files?

Thanks,
Aruna

**Comment by izmal** [comment]
You can download IPSW from https://ipsw.me.
12.4.6 for iPhone 6s and older
13.4 from 6s to X
13.4 arm64e for iPhone X and newest

**Comment by ArunaYarra** [comment]
> You can download IPSW from https://ipsw.me.
> 12.4.6 for iPhone 6s and older
> 13.4 from 6s to X
> 13.4 arm64e for iPhone X and newest

Thanks for your update.

But when I extracted the 13.4 arm64 firmware file to dmg, and when I open that dmg file I'm getting "Image not recognised" error.

Can you please help me with how can I get it?

**Comment by izmal** [comment]
I uploaded symbols for `13.4 arm64`. You can get zip-archive [here](https://drive.google.com/open?id=1CBMtyn5WJkSY1DouXmNKrCOG_4VkmVs5)

**Comment by ArunaYarra** [comment]
> I uploaded symbols for `13.4 arm64`. You can get zip-archive [here](https://drive.google.com/open?id=1CBMtyn5WJkSY1DouXmNKrCOG_4VkmVs5)

Hey, thanks a lot.
But these are arm64e symbols. I'm expecting arm64 symbols. Can you please provide me?

Thanks,
Aruna

**Comment by izmal** [comment]
Oops, sorry.
[13.4 arm64](https://drive.google.com/open?id=1SQ_GBvvzAsJrelFymT67QD_XVDqaj7mp)

**Comment by ArunaYarra** [comment]
Thanks
