### ISSUE TITLE
Potentially store the files against the repository

### ISSUE THREAD

**Issue by whitfin** [Zuikyo/iOS-System-Symbols#2]
Is it possible to store the files actually inside the repository, maybe using the large file storage? This would make it easier to script sync jobs to keep symbols up to date, etc. I don't think you would need separate downloads for China in that case either?

https://git-lfs.github.com/ might be interesting for this, but I've never personally used it.

**Comment by Zuikyo** [comment]
Thanks for your advertisement, git LFS is a cool option. 
But these symbol files are too big (nearly 40 GB now), and git LFS only give us 1 GB storage for free. I think it's not that worthwhile to pay for these symbol files.
And it's not necessary to put symbol files under version control. In China, Baidu Netdisk provides much faster download speeds. So I think put them in some cloud drive is fine.
