### ISSUE TITLE
iOS 12.4.6 iOS System symbol files

### ISSUE THREAD

**Issue by ShowHandAce** [Zuikyo/iOS-System-Symbols#20]
最近后台看到了12.4.6的堆栈,多方查找无果.如果大佬收集到,辛苦大佬上传一下,多谢~~

**Comment by Zuikyo** [comment]
You can download 12.4.6 firmware at here: [https://ipsw.me/12.4.6](https://ipsw.me/12.4.6), and get symbols by yourself: [Extract Symbols from Firmware](https://github.com/Zuikyo/iOS-System-Symbols#extract-symbols-from-firmware)

**Comment by ShowHandAce** [comment]
@Zuikyo Thanks~
