### ISSUE TITLE
when update iOS 14 Symbols？

### ISSUE THREAD

**Issue by Jack-Rain** [Zuikyo/iOS-System-Symbols#26]
when update iOS 14 Symbols？

**Comment by zhilinghuang** [comment]
When are you going to update iOS 14 symbols, please.

**Comment by Zuikyo** [comment]
You can extract symbols with you own: [extract-symbols-from-firmware](https://github.com/Zuikyo/iOS-System-Symbols#extract-symbols-from-firmware)

**Comment by Jack-Rain** [comment]
> You can extract symbols with you own: [extract-symbols-from-firmware](https://github.com/Zuikyo/iOS-System-Symbols#extract-symbols-from-firmware)

yeah I have wrote a script to do that。

**Comment by CXTretar** [comment]
I made a supplement to symol files here.
https://github.com/CXTretar/iOS-System-Symbols-Supplement

**Comment by Zuikyo** [comment]
Since iOS 10, the system firmware is not encrypted, so you can just get those symbols by yourself ([extract-symbols-from-firmware](https://github.com/Zuikyo/iOS-System-Symbols#extract-symbols-from-firmware)). And I will not update the list any more.
