### ISSUE TITLE
Merge Symbol Error for arm64 and arm64e

### ISSUE THREAD

**Issue by ferlixwangg** [Zuikyo/iOS-System-Symbols#27]
Hi, I have been trying to merge device symbols from iOS 14.4.2 arm64 and arm64e using the `merge_symbols.sh`. However, I keep on facing this issue (like the one in the screenshot) and some other fatal errors after the script is finished running:

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/17472033/116857468-0dca5d00-ac27-11eb-86bf-ff081d55ef83.png">
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/17472033/116857215-a4e2e500-ac26-11eb-8870-780d52a53c34.png">

Is there anything that I missed?
I obtain the device symbols from here for both the arm64 (https://ipsw.me/download/iPhone8,1/18D70) and arm64e (https://ipsw.me/download/iPhone13,1/18D70)

**Comment by Zuikyo** [comment]
I find out that it's not necessary to merge arm64e with other symbols.
Just add a `arm64e` prefix in the symbol folders like `14.4.2 (18D70) arm64e`. And for arm64 and armv7s, keep them in `14.4.2 (18D70)`.
