### ISSUE TITLE
iOS 16 ipsw /System/Library/Caches/com.apple.dyld disappears

### ISSUE THREAD

**Issue by HuangXiZhu** [Zuikyo/iOS-System-Symbols#32]
I found that dyld cache path can not be found in iOS16 firmware, please tell me if you occur the same question.

**Comment by HuangXiZhu** [comment]
@ikem-krueger @Zuikyo

**Comment by Zuikyo** [comment]
It's moved to another .dmg file (the secondary big file in ipsw). And you need install XCode 14 to extract the dyld_shared_cache_arm64e file.

**Comment by thet0aster** [comment]
How do I open the second dmg file in XCode 14? I've tried dragging and dropping the file into XCode but I can't seem to get it to work. Is there any other way to extract the iOS 16 shared cache?
