### ISSUE TITLE
Add symbols for `arm64e` CPU architecture

### ISSUE THREAD

**Issue by EmingK** [Zuikyo/iOS-System-Symbols#4]
iPhone XS/XR uses new cpu architecture `arm64e` since iOS 12.0, which need to be merged to the symbol files.

**Comment by Zuikyo** [comment]
That's interesting. I will download a firmware of XS/XR to see what's the difference.

If you need those `arm64e` symbols now, you can try [Extract Symbols from Firmware](
https://github.com/Zuikyo/iOS-System-Symbols#extract-symbols-from-firmware).

**Comment by Zuikyo** [comment]
New symbols are added now.
