### ISSUE TITLE
Possible to add 12.1.4 symbols to GDrive shares?

### ISSUE THREAD

**Issue by cgwyllie** [Zuikyo/iOS-System-Symbols#7]
Hi,

Thanks for all the work collecting these symbol files, it's really useful.

I was wondering if it would be possible to update the Google Drive folder with the 12.1.4 symbols? We can see they are already present in the Baidu share, but that's not easy for us to access outside China.

Thanks,
  Chris

**Comment by Zuikyo** [comment]
I just checked. 12.1.4 was uploaded, but someone else deleted it from the Google Drive. 
Maybe I should not let anybody else to change them. 
I'm uploading it now.

**Comment by Zuikyo** [comment]
12.1.4 is in the Google Driver, and files are readonly now.
