### ISSUE TITLE
UIKitCore符号表

### ISSUE THREAD

**Issue by ShowHandAce** [Zuikyo/iOS-System-Symbols#8]
首先感谢大神收集分享系统符号表,非常全面!
我在解析部分崩溃堆栈的时候发现一个叫UIKitCore的系统库,直接用UIKit解析不出来,也并没有找到对应名称的符号表,请问关于这个库应该怎么解析您清楚吗?
多谢~

**Comment by Zuikyo** [comment]
UIKitCore 是另一个库，和 UIKit 不是同一个。好像是 iOS 12 之后，苹果把大部分 UIKit 的实现都挪到 UIKitCore 里了。可以在`/Symbols/System/Library/PrivateFrameworks/UIKitCore.framework`里找到。

**Comment by ShowHandAce** [comment]
> UIKitCore 是另一个库，和 UIKit 不是同一个。好像是 iOS 12 之后，苹果把大部分 UIKit 的实现都挪到 UIKitCore 里了。可以在`/Symbols/System/Library/PrivateFrameworks/UIKitCore.framework`里找到。

找到了~非常感谢~
