### ISSUE TITLE
dsc_extractor in Xcode 11 doesn't merge arm64 and arm64e

### ISSUE THREAD

**Issue by li8911255** [Zuikyo/iOS-System-Symbols#9]
如题，Xcode 11 不会合并俩符号文件，后一次生成的会覆盖前一次生成的。

Xcode 10 正常，不知道大佬有遇到过没？是否有好的解决办法？多谢

**Comment by Zuikyo** [comment]
暂时没有解决办法，现在我还是使用的 Xcode 10 来处理符号

**Comment by Zuikyo** [comment]
After Xcode 11 for iOS 13.2, `dsc_extractor` won't merge different architectures files. 
We need to merge symbols with `lipo` command. 
You can try my script [merge_symbols.sh](https://github.com/Zuikyo/iOS-System-Symbols/tree/master/tools/merge_symbols.sh) : ` sh merge_symbols.sh <path_to_extracted_arm64e_symbols> <path_to_extracted_arm64_symbols>`

**Comment by li8911255** [comment]
thx
